export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const CHANGE_BOTTOM_OFFSET = 'CHANGE_BOTTOM_OFFSET';

export const REQUEST_POINT_ADDRESS = 'REQUEST_POINT_ADDRESS';
export const REQUEST_POINT_ADDRESS_SUCCESS = 'REQUEST_POINT_ADDRESS_SUCCESS';
export const REQUEST_POINT_ADDRESS_FAILED = 'REQUEST_POINT_ADDRESS_FAILED';

export const REQUEST_DESTINATION_POINT = 'REQUEST_DESTINATION_POINT';
export const REQUEST_DESTINATION_POINT_SUCCESS = 'REQUEST_DESTINATION_POINT_SUCCESS';
export const REQUEST_DESTINATION_POINT_FAILED = 'REQUEST_DESTINATION_POINT_FAILED';