export const CHANGE_BOTTOM_OFFSET = 'CHANGE_BOTTOM_OFFSET';

export const REQUEST_POINT_ADDRESS = 'REQUEST_POINT_ADDRESS';
export const REQUEST_POINT_ADDRESS_SUCCESS = 'REQUEST_POINT_ADDRESS_SUCCESS';
export const REQUEST_POINT_ADDRESS_FAILED = 'REQUEST_POINT_ADDRESS_FAILED';

export const REQUEST_DESTINATION_POINT = 'REQUEST_DESTINATION_POINT';
export const REQUEST_DESTINATION_POINT_SUCCESS = 'REQUEST_DESTINATION_POINT_SUCCESS';
export const REQUEST_DESTINATION_POINT_FAILED = 'REQUEST_DESTINATION_POINT_FAILED';

export const REQUEST_DIRECTION_ROUTE = 'REQUEST_DIRECTION_ROUTE';
export const REQUEST_DIRECTION_ROUTE_SUCCESS = 'REQUEST_DIRECTION_ROUTE_SUCCESS';
export const REQUEST_DIRECTION_ROUTE_FAILED = 'REQUEST_DIRECTION_ROUTE_FAILED';